import { chromium } from "playwright";
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const page = await browser.newPage({ viewport: { width: 375, height: 812 } });
await page.route("**/api/**", (r) => r.fulfill({ status: 200, contentType: "application/json", body: "{}" }));
await page.addInitScript(() => localStorage.setItem("launchpad.entered", "1"));
await page.goto("http://localhost:5173/", { waitUntil: "domcontentloaded" });
await page.waitForTimeout(800);
const tabs = page.locator(".tabs");
const box = await tabs.boundingBox();
const vh = 812;
console.log("tabs box:", JSON.stringify(box), "fixed-bottom:", box && box.y + box.height >= vh - 2);
const btn = tabs.locator("button").first();
const bb = await btn.boundingBox();
console.log("first tab target:", bb.width.toFixed(0), "x", bb.height.toFixed(0));
await page.screenshot({ path: "design-review/p3-mobile-bottombar.png" });
await browser.close();
